
puts "seeding"
h1 = Hotel.create!(name:"Sorova" ,hotel_type:"4 star" ,city:"Kampala", address:"Kingston Avenue", distance:"400",photo:"https://cf.bstatic.com/xdata/images/hotel/max1280x900/261707367.jpg?k=cbacfdeb8404af56a1a94812575d96f6b80f6740fd491d02c6fc3912a16d8757&o=&hp=1",description:" Street Apartments has accommodations with air conditioning and free WiFi. The units come with hardwood floors and feature a fully equipped kitchenette with a microwave, a flat-screen TV, and a private bathroom with shower and a hairdryer. A fridge is also offered, as well as an electric tea pot and a coffee machine. Popular points of interest near the apartment include
Cloth Hall, Main Market Square and Town Hall Tower",ratings:8,cheapest_price:200)
h2 = Hotel.create!(name:"Sarit", hotel_type:"5 star" ,city:"Nairobi", address:"Moi Avenue", distance:"250",photo:"https://cf.bstatic.com/xdata/images/hotel/max1280x900/261707367.jpg?k=cbacfdeb8404af56a1a94812575d96f6b80f6740fd491d02c6fc3912a16d8757&o=&hp=1",description: "Street Apartments has accommodations with air conditioning and free WiFi. The units come with hardwood floors and feature a fully equipped kitchenette with a microwave, a flat-screen TV, and a private bathroom with shower and a hairdryer. A fridge is also offered, as well as an electric tea pot and a coffee machine. Popular points of interest near the apartment include
Cloth Hall, Main Market Square and Town Hall Tower",ratings:9,cheapest_price:200)
h3 = Hotel.create!(name:"Hilton", hotel_type:" 3star" ,city:"Dodoma", address:"Nyerere Avenue", distance:"600",photo: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/261707367.jpg?k=cbacfdeb8404af56a1a94812575d96f6b80f6740fd491d02c6fc3912a16d8757&o=&hp=1",description: "Street Apartments has accommodations with air conditioning and free WiFi. The units come with hardwood floors and feature a fully equipped kitchenette with a microwave, a flat-screen TV, and a private bathroom with shower and a hairdryer. A fridge is also offered, as well as an electric tea pot and a coffee machine. Popular points of interest near the apartment include
Cloth Hall, Main Market Square and Town Hall Tower", ratings:6,cheapest_price:200)
h4 = Hotel.create!(name:"Lotus", hotel_type:"2  star" ,city:"Kampala", address:"Junior Avenue", distance:"800",photo:"https://cf.bstatic.com/xdata/images/hotel/max1280x900/261707389.jpg?k=52156673f9eb6d5d99d3eed9386491a0465ce6f3b995f005ac71abc192dd5827&o=&hp=1",description: "Street Apartments has accommodations with air conditioning and free WiFi. The units come with hardwood floors and feature a fully equipped kitchenette with a microwave, a flat-screen TV, and a private bathroom with shower and a hairdryer. A fridge is also offered, as well as an electric tea pot and a coffee machine. Popular points of interest near the apartment include
Cloth Hall, Main Market Square and Town Hall Tower",ratings:8,cheapest_price:200)
h5 = Hotel.create!(name:"GardenCity", hotel_type:"2  star" ,city:"Kampala", address:"Junior Avenue", distance:"800",photo:"https://cf.bstatic.com/xdata/images/hotel/max1280x900/261707389.jpg?k=52156673f9eb6d5d99d3eed9386491a0465ce6f3b995f005ac71abc192dd5827&o=&hp=1",description: "Street Apartments has accommodations with air conditioning and free WiFi. The units come with hardwood floors and feature a fully equipped kitchenette with a microwave, a flat-screen TV, and a private bathroom with shower and a hairdryer. A fridge is also offered, as well as an electric tea pot and a coffee machine. Popular points of interest near the apartment include
    Cloth Hall, Main Market Square and Town Hall Tower",ratings:8,cheapest_price:200)
    


puts "done"